import { createStorageContentSignature } from '@apify/utilities';

describe('createStorageContentSignature()', () => {
    it('should set expiresAt to 0 for a non-expiring signature', () => {
        const secretKey = 'hmac-secret-key';
        const message = 'hmac-message-to-be-authenticated';

        const signature = createStorageContentSignature({
            resourceId: message,
            urlSigningSecretKey: secretKey,
            expiresInMillis: undefined,
        });

        const [version, expiresAt, hmac] = Buffer.from(signature, 'base64url').toString('utf8').split('.');
        expect(signature).toBe('MC4wLjFzcGd6VUhXaGpiR3pVSEVTeWJMVQ');
        expect(version).toBe('0');
        expect(expiresAt).toBe('0');
        // This HMAC should match HMAC generated by Python function.
        expect(hmac).toBe('1spgzUHWhjbGzUHESybLU');
    });

    it('should create a signature with a future expiration timestamp when expiresInMillis is provided', () => {
        const secretKey = 'hmac-secret-key';
        const message = 'hmac-message-to-be-authenticated';

        const signature = createStorageContentSignature({
            resourceId: message,
            urlSigningSecretKey: secretKey,
            expiresInMillis: 10000,
        });

        const [version, expiresAt] = Buffer.from(signature, 'base64url').toString('utf8').split('.');
        expect(version).toBe('0');
        expect(expiresAt).not.toBe('0');
    });
});
