export const CATEGORY_GROUP = {
    USE_CASE: 'USE_CASE',
    INDUSTRY: 'INDUSTRY',
    DOMAIN: 'DOMAIN',
    OUTPUT: 'OUTPUT',
    LABEL: 'LABEL',
} as const;
export type CATEGORY_GROUP = (typeof CATEGORY_GROUP)[keyof typeof CATEGORY_GROUP];

type ActorCategoryShape = {
    id: string;
    name: string;
    parentCategoryId: string | null;
    group: CATEGORY_GROUP;
    /** Hierarchy depth within the category group. Only used for USE_CASE categories; null for all others. */
    depth: 1 | 2 | 3 | null;
};

export const USE_CASE_CATEGORIES = [
    {
        id: 'OTHER',
        name: 'Uncategorized',
        parentCategoryId: null,
        group: CATEGORY_GROUP.USE_CASE,
        depth: 1,
    },
    {
        id: 'GENERATE_LEADS',
        name: 'Generate leads',
        parentCategoryId: null,
        group: CATEGORY_GROUP.USE_CASE,
        depth: 1,
    },
    {
        id: 'RESEARCH_MARKETS_AND_COMPETITORS',
        name: 'Research markets & competitors',
        parentCategoryId: null,
        group: CATEGORY_GROUP.USE_CASE,
        depth: 1,
    },
    {
        id: 'TRACK_COMPETITORS',
        name: 'Track competitors',
        parentCategoryId: 'RESEARCH_MARKETS_AND_COMPETITORS',
        group: CATEGORY_GROUP.USE_CASE,
        depth: 2,
    },
    {
        id: 'TRACK_TRENDS',
        name: 'Track trends',
        parentCategoryId: 'RESEARCH_MARKETS_AND_COMPETITORS',
        group: CATEGORY_GROUP.USE_CASE,
        depth: 2,
    },
    {
        id: 'BRAND_MONITORING',
        name: 'Brand monitoring',
        parentCategoryId: null,
        group: CATEGORY_GROUP.USE_CASE,
        depth: 1,
    },
    {
        id: 'ANALYZE_SENTIMENT',
        name: 'Analyze sentiment',
        parentCategoryId: 'BRAND_MONITORING',
        group: CATEGORY_GROUP.USE_CASE,
        depth: 2,
    },
    {
        id: 'ANALYZE_SEO_AND_MARKETING',
        name: 'Analyze SEO & marketing',
        parentCategoryId: null,
        group: CATEGORY_GROUP.USE_CASE,
        depth: 1,
    },
    {
        id: 'ANALYZE_BACKLINKS',
        name: 'Analyze backlinks',
        parentCategoryId: 'ANALYZE_SEO_AND_MARKETING',
        group: CATEGORY_GROUP.USE_CASE,
        depth: 2,
    },
    {
        id: 'RUN_WEBSITE_AUDITS',
        name: 'Run website audits',
        parentCategoryId: 'ANALYZE_SEO_AND_MARKETING',
        group: CATEGORY_GROUP.USE_CASE,
        depth: 2,
    },
    {
        id: 'TRACK_PRODUCTS_AND_PRICES',
        name: 'Track products & prices',
        parentCategoryId: null,
        group: CATEGORY_GROUP.USE_CASE,
        depth: 1,
    },
    {
        id: 'COLLECT_AND_DISTRIBUTE_CONTENT',
        name: 'Collect & distribute content',
        parentCategoryId: null,
        group: CATEGORY_GROUP.USE_CASE,
        depth: 1,
    },
    {
        id: 'MAP_BUSINESSES_BY_TYPE_AND_LOCATION',
        name: 'Map businesses by type & location',
        parentCategoryId: 'COLLECT_AND_DISTRIBUTE_CONTENT',
        group: CATEGORY_GROUP.USE_CASE,
        depth: 2,
    },
    {
        id: 'DEVELOPER_TOOLS',
        name: 'Developer tools',
        parentCategoryId: null,
        group: CATEGORY_GROUP.USE_CASE,
        depth: 1,
    },
    {
        id: 'MONITOR_AND_ALERT_ON_WEBSITE_CHANGES',
        name: 'Monitor & alert on website changes',
        parentCategoryId: 'DEVELOPER_TOOLS',
        group: CATEGORY_GROUP.USE_CASE,
        depth: 2,
    },
    {
        id: 'TRANSFORM_AND_PROCESS_DATA',
        name: 'Transform & process data',
        parentCategoryId: 'DEVELOPER_TOOLS',
        group: CATEGORY_GROUP.USE_CASE,
        depth: 2,
    },
    {
        id: 'BUILD_FEEDS_AND_DIRECTORIES',
        name: 'Build feeds & directories',
        parentCategoryId: 'COLLECT_AND_DISTRIBUTE_CONTENT',
        group: CATEGORY_GROUP.USE_CASE,
        depth: 2,
    },
    {
        id: 'BUILD_AI_TRAINING_DATA',
        name: 'Build AI training data',
        parentCategoryId: 'COLLECT_AND_DISTRIBUTE_CONTENT',
        group: CATEGORY_GROUP.USE_CASE,
        depth: 2,
    },
    {
        id: 'SCRAPE_FORUMS_AND_COMMUNITY_DISCUSSIONS',
        name: 'Scrape forums & community discussions',
        parentCategoryId: 'BUILD_AI_TRAINING_DATA',
        group: CATEGORY_GROUP.USE_CASE,
        depth: 3,
    },
    {
        id: 'EXTRACT_VIDEO_TRANSCRIPTS_AND_CAPTIONS',
        name: 'Extract video transcripts & captions',
        parentCategoryId: 'BUILD_AI_TRAINING_DATA',
        group: CATEGORY_GROUP.USE_CASE,
        depth: 3,
    },
    {
        id: 'COLLECT_ACADEMIC_PAPERS',
        name: 'Collect academic papers',
        parentCategoryId: 'BUILD_AI_TRAINING_DATA',
        group: CATEGORY_GROUP.USE_CASE,
        depth: 3,
    },
    {
        id: 'CONVERT_WEB_PAGES_TO_AI_READY_TEXT',
        name: 'Convert web pages to AI-ready text',
        parentCategoryId: 'BUILD_AI_TRAINING_DATA',
        group: CATEGORY_GROUP.USE_CASE,
        depth: 3,
    },
    {
        id: 'DOWNLOAD_AND_ARCHIVE_MEDIA',
        name: 'Download & archive media',
        parentCategoryId: 'COLLECT_AND_DISTRIBUTE_CONTENT',
        group: CATEGORY_GROUP.USE_CASE,
        depth: 2,
    },
    {
        id: 'GET_DEAL_AND_RESTOCK_ALERTS',
        name: 'Get deal & restock alerts',
        parentCategoryId: 'TRACK_PRODUCTS_AND_PRICES',
        group: CATEGORY_GROUP.USE_CASE,
        depth: 2,
    },
    {
        id: 'TRACK_FINANCIAL_MARKETS_AND_TRADING_DATA',
        name: 'Track financial markets & trading data',
        parentCategoryId: 'RESEARCH_MARKETS_AND_COMPETITORS',
        group: CATEGORY_GROUP.USE_CASE,
        depth: 2,
    },
    {
        id: 'PROFILE_COMPANIES_AND_DUE_DILIGENCE',
        name: 'Profile companies & due diligence',
        parentCategoryId: 'RESEARCH_MARKETS_AND_COMPETITORS',
        group: CATEGORY_GROUP.USE_CASE,
        depth: 2,
    },
    {
        id: 'ENRICH_COMPANY_PROFILES',
        name: 'Enrich company profiles',
        parentCategoryId: 'PROFILE_COMPANIES_AND_DUE_DILIGENCE',
        group: CATEGORY_GROUP.USE_CASE,
        depth: 3,
    },
    {
        id: 'GET_COMPANY_REGISTRIES_AND_FILINGS',
        name: 'Get company registries & filings',
        parentCategoryId: 'PROFILE_COMPANIES_AND_DUE_DILIGENCE',
        group: CATEGORY_GROUP.USE_CASE,
        depth: 3,
    },
    {
        id: 'RESEARCH_B2B_SUPPLIERS_AND_TRADE_PARTNERS',
        name: 'Research B2B suppliers & trade partners',
        parentCategoryId: 'PROFILE_COMPANIES_AND_DUE_DILIGENCE',
        group: CATEGORY_GROUP.USE_CASE,
        depth: 3,
    },
    {
        id: 'RESEARCH_FUNDING_AND_FINANCIALS',
        name: 'Research funding & financials',
        parentCategoryId: 'PROFILE_COMPANIES_AND_DUE_DILIGENCE',
        group: CATEGORY_GROUP.USE_CASE,
        depth: 3,
    },
    {
        id: 'CHECK_COMPLIANCE_AND_ESG',
        name: 'Check compliance & ESG',
        parentCategoryId: 'PROFILE_COMPANIES_AND_DUE_DILIGENCE',
        group: CATEGORY_GROUP.USE_CASE,
        depth: 3,
    },
    {
        id: 'DISCOVER_STARTUPS_AND_NEW_LAUNCHES',
        name: 'Discover startups & new launches',
        parentCategoryId: 'RESEARCH_MARKETS_AND_COMPETITORS',
        group: CATEGORY_GROUP.USE_CASE,
        depth: 2,
    },
    {
        id: 'BUILD_B2B_PROSPECT_LISTS',
        name: 'Build B2B prospect lists',
        parentCategoryId: 'GENERATE_LEADS',
        group: CATEGORY_GROUP.USE_CASE,
        depth: 2,
    },
    {
        id: 'LOCAL_BUSINESS_PROSPECTING',
        name: 'Local business prospecting',
        parentCategoryId: 'GENERATE_LEADS',
        group: CATEGORY_GROUP.USE_CASE,
        depth: 2,
    },
    {
        id: 'INFLUENCER_AND_CREATOR_OUTREACH',
        name: 'Influencer & creator outreach',
        parentCategoryId: 'GENERATE_LEADS',
        group: CATEGORY_GROUP.USE_CASE,
        depth: 2,
    },
    {
        id: 'SPOT_VIRAL_CONTENT_AND_CREATORS',
        name: 'Spot viral content & creators',
        parentCategoryId: 'TRACK_TRENDS',
        group: CATEGORY_GROUP.USE_CASE,
        depth: 3,
    },
    {
        id: 'RESEARCH_KEYWORDS_AND_SEARCH_DEMAND',
        name: 'Research keywords & search demand',
        parentCategoryId: 'TRACK_TRENDS',
        group: CATEGORY_GROUP.USE_CASE,
        depth: 3,
    },
    {
        id: 'TRACK_TOPICS_AND_MARKET_SHIFTS',
        name: 'Track topics & market shifts',
        parentCategoryId: 'TRACK_TRENDS',
        group: CATEGORY_GROUP.USE_CASE,
        depth: 3,
    },
    {
        id: 'BROWSER_AUTOMATION',
        name: 'Browser automation and testing',
        parentCategoryId: 'DEVELOPER_TOOLS',
        group: CATEGORY_GROUP.USE_CASE,
        depth: 2,
    },
    {
        id: 'AI_INTEGRATIONS',
        name: 'AI and LLM integrations',
        parentCategoryId: 'DEVELOPER_TOOLS',
        group: CATEGORY_GROUP.USE_CASE,
        depth: 2,
    },
    {
        id: 'PROCESS_AND_CONVERT_MEDIA',
        name: 'Process & convert media',
        parentCategoryId: 'DEVELOPER_TOOLS',
        group: CATEGORY_GROUP.USE_CASE,
        depth: 2,
    },
    {
        id: 'ORCHESTRATE_WORKFLOWS_AND_AUTOMATION',
        name: 'Orchestrate workflows & automation',
        parentCategoryId: 'DEVELOPER_TOOLS',
        group: CATEGORY_GROUP.USE_CASE,
        depth: 2,
    },
    {
        id: 'TRACK_SEARCH_RANKINGS',
        name: 'Track search rankings',
        parentCategoryId: 'ANALYZE_SEO_AND_MARKETING',
        group: CATEGORY_GROUP.USE_CASE,
        depth: 2,
    },
    {
        id: 'ANALYZE_DOMAIN_AUTHORITY',
        name: 'Analyze domain authority & metrics',
        parentCategoryId: 'ANALYZE_SEO_AND_MARKETING',
        group: CATEGORY_GROUP.USE_CASE,
        depth: 2,
    },
    {
        id: 'EXTRACT_WEBSITE_METADATA',
        name: 'Extract website metadata & tech stacks',
        parentCategoryId: 'ANALYZE_SEO_AND_MARKETING',
        group: CATEGORY_GROUP.USE_CASE,
        depth: 2,
    },
    {
        id: 'COLLECT_NEWS_AND_ARTICLES',
        name: 'Collect news & articles',
        parentCategoryId: 'COLLECT_AND_DISTRIBUTE_CONTENT',
        group: CATEGORY_GROUP.USE_CASE,
        depth: 2,
    },
    {
        id: 'COLLECT_AND_ANALYZE_CUSTOMER_REVIEWS',
        name: 'Collect & analyze customer reviews',
        parentCategoryId: 'RESEARCH_MARKETS_AND_COMPETITORS',
        group: CATEGORY_GROUP.USE_CASE,
        depth: 2,
    },
    {
        id: 'RESEARCH_APP_STORES_AND_SOFTWARE_MARKETS',
        name: 'Research app stores & software markets',
        parentCategoryId: 'RESEARCH_MARKETS_AND_COMPETITORS',
        group: CATEGORY_GROUP.USE_CASE,
        depth: 2,
    },
    {
        id: 'EMAIL_PHONE_EXTRACTION',
        name: 'Email & phone extraction',
        parentCategoryId: 'GENERATE_LEADS',
        group: CATEGORY_GROUP.USE_CASE,
        depth: 2,
    },
    {
        id: 'PRODUCT_SOURCING_AND_PROCUREMENT',
        name: 'Product sourcing & procurement',
        parentCategoryId: 'TRACK_PRODUCTS_AND_PRICES',
        group: CATEGORY_GROUP.USE_CASE,
        depth: 2,
    },
    {
        id: 'FIND_RESALE_AND_ARBITRAGE_DEALS',
        name: 'Find resale & arbitrage deals',
        parentCategoryId: 'TRACK_PRODUCTS_AND_PRICES',
        group: CATEGORY_GROUP.USE_CASE,
        depth: 2,
    },
    {
        id: 'BUILD_MARKET_DATASETS',
        name: 'Build market datasets',
        parentCategoryId: 'RESEARCH_MARKETS_AND_COMPETITORS',
        group: CATEGORY_GROUP.USE_CASE,
        depth: 2,
    },
    {
        id: 'FIND_DEALS_AND_BUY_OPPORTUNITIES',
        name: 'Find deals & buy opportunities',
        parentCategoryId: 'RESEARCH_MARKETS_AND_COMPETITORS',
        group: CATEGORY_GROUP.USE_CASE,
        depth: 2,
    },
    {
        id: 'FIND_AND_ENRICH_CREATOR_CONTACTS',
        name: 'Find & enrich creator contacts',
        parentCategoryId: 'INFLUENCER_AND_CREATOR_OUTREACH',
        group: CATEGORY_GROUP.USE_CASE,
        depth: 3,
    },
    {
        id: 'DISCOVER_AND_PROFILE_CREATORS',
        name: 'Discover & profile creators',
        parentCategoryId: 'INFLUENCER_AND_CREATOR_OUTREACH',
        group: CATEGORY_GROUP.USE_CASE,
        depth: 3,
    },
    {
        id: 'ANALYZE_CREATOR_CONTENT_ENGAGEMENT',
        name: 'Analyze creator content & engagement',
        parentCategoryId: 'INFLUENCER_AND_CREATOR_OUTREACH',
        group: CATEGORY_GROUP.USE_CASE,
        depth: 3,
    },
    {
        id: 'VET_AND_SCORE_CREATORS',
        name: 'Vet & score creators',
        parentCategoryId: 'INFLUENCER_AND_CREATOR_OUTREACH',
        group: CATEGORY_GROUP.USE_CASE,
        depth: 3,
    },
    {
        id: 'AUTOMATE_INFLUENCER_OUTREACH',
        name: 'Automate influencer outreach',
        parentCategoryId: 'INFLUENCER_AND_CREATOR_OUTREACH',
        group: CATEGORY_GROUP.USE_CASE,
        depth: 3,
    },
    {
        id: 'DISCOVER_LEADS_FROM_ENGAGEMENTS',
        name: 'Discover leads from engagements',
        parentCategoryId: 'GENERATE_LEADS',
        group: CATEGORY_GROUP.USE_CASE,
        depth: 2,
    },
    {
        id: 'LEAD_ENRICHMENT_AND_VALIDATION',
        name: 'Lead enrichment & validation',
        parentCategoryId: 'GENERATE_LEADS',
        group: CATEGORY_GROUP.USE_CASE,
        depth: 2,
    },
    {
        id: 'AUTOMATE_OUTREACH_CAMPAIGNS',
        name: 'Automate outreach campaigns',
        parentCategoryId: 'GENERATE_LEADS',
        group: CATEGORY_GROUP.USE_CASE,
        depth: 2,
    },
    {
        id: 'BUILD_LARGE_PROSPECT_DATABASES',
        name: 'Build large prospect databases',
        parentCategoryId: 'BUILD_B2B_PROSPECT_LISTS',
        group: CATEGORY_GROUP.USE_CASE,
        depth: 3,
    },
    {
        id: 'IDENTIFY_DECISION_MAKERS',
        name: 'Identify decision-makers',
        parentCategoryId: 'BUILD_B2B_PROSPECT_LISTS',
        group: CATEGORY_GROUP.USE_CASE,
        depth: 3,
    },
    {
        id: 'TRACK_ONLINE_CONVERSATIONS_AND_ENGAGEMENT',
        name: 'Track online conversations & audience engagement',
        parentCategoryId: 'BRAND_MONITORING',
        group: CATEGORY_GROUP.USE_CASE,
        depth: 2,
    },
    {
        id: 'MONITOR_HASHTAG_AND_KEYWORD_MENTIONS',
        name: 'Monitor hashtag & keyword mentions',
        parentCategoryId: 'BRAND_MONITORING',
        group: CATEGORY_GROUP.USE_CASE,
        depth: 2,
    },
    {
        id: 'COLLECT_REVIEWS_AND_RATINGS',
        name: 'Collect reviews & ratings',
        parentCategoryId: 'BRAND_MONITORING',
        group: CATEGORY_GROUP.USE_CASE,
        depth: 2,
    },
    {
        id: 'CONVERT_BETWEEN_DATA_FORMATS',
        name: 'Convert between data formats',
        parentCategoryId: 'TRANSFORM_AND_PROCESS_DATA',
        group: CATEGORY_GROUP.USE_CASE,
        depth: 3,
    },
    {
        id: 'CLEAN_VALIDATE_AND_DEDUPLICATE_DATASETS',
        name: 'Clean, validate & deduplicate datasets',
        parentCategoryId: 'TRANSFORM_AND_PROCESS_DATA',
        group: CATEGORY_GROUP.USE_CASE,
        depth: 3,
    },
    {
        id: 'EXPORT_AND_SYNC_DATA_TO_EXTERNAL_STORAGE',
        name: 'Export & sync data to external storage',
        parentCategoryId: 'TRANSFORM_AND_PROCESS_DATA',
        group: CATEGORY_GROUP.USE_CASE,
        depth: 3,
    },
    {
        id: 'VALIDATE_AND_RESOLVE_IDENTIFIERS',
        name: 'Validate & resolve identifiers',
        parentCategoryId: 'TRANSFORM_AND_PROCESS_DATA',
        group: CATEGORY_GROUP.USE_CASE,
        depth: 3,
    },
    {
        id: 'PREPARE_DATA_FOR_LLM_AND_RAG',
        name: 'Prepare data for LLM & RAG pipelines',
        parentCategoryId: 'TRANSFORM_AND_PROCESS_DATA',
        group: CATEGORY_GROUP.USE_CASE,
        depth: 3,
    },
    {
        id: 'GENERATE_SYNTHETIC_AND_MOCK_DATA',
        name: 'Generate synthetic & mock data',
        parentCategoryId: 'TRANSFORM_AND_PROCESS_DATA',
        group: CATEGORY_GROUP.USE_CASE,
        depth: 3,
    },
    {
        id: 'EXTRACT_VEHICLE_LISTINGS_AND_AUTOMOTIVE_DATA',
        name: 'Extract vehicle listings & automotive parts data',
        parentCategoryId: 'TRACK_PRODUCTS_AND_PRICES',
        group: CATEGORY_GROUP.USE_CASE,
        depth: 2,
    },
    {
        id: 'SCRAPE_GROCERY_PRICES_AND_FOOD_DELIVERY_MENUS',
        name: 'Scrape grocery prices & food delivery menus',
        parentCategoryId: 'TRACK_PRODUCTS_AND_PRICES',
        group: CATEGORY_GROUP.USE_CASE,
        depth: 2,
    },
    {
        id: 'EXTRACT_TRAVEL_AND_HOSPITALITY_PRICING',
        name: 'Extract travel & hospitality pricing',
        parentCategoryId: 'TRACK_PRODUCTS_AND_PRICES',
        group: CATEGORY_GROUP.USE_CASE,
        depth: 2,
    },
    {
        id: 'SCRAPE_CLASSIFIEDS_AND_P2P_MARKETPLACE_LISTINGS',
        name: 'Scrape classifieds & peer-to-peer marketplace listings',
        parentCategoryId: 'TRACK_PRODUCTS_AND_PRICES',
        group: CATEGORY_GROUP.USE_CASE,
        depth: 2,
    },
] as const satisfies readonly ActorCategoryShape[];

export const INDUSTRY_CATEGORIES = [
    {
        id: 'SOCIAL_MEDIA',
        name: 'Social media',
        parentCategoryId: null,
        group: CATEGORY_GROUP.INDUSTRY,
        depth: null,
    },
    {
        id: 'ECOMMERCE',
        name: 'E-commerce',
        parentCategoryId: null,
        group: CATEGORY_GROUP.INDUSTRY,
        depth: null,
    },
    {
        id: 'TRAVEL_AND_HOSPITALITY',
        name: 'Travel & hospitality',
        parentCategoryId: null,
        group: CATEGORY_GROUP.INDUSTRY,
        depth: null,
    },
    {
        id: 'REAL_ESTATE',
        name: 'Real estate',
        parentCategoryId: null,
        group: CATEGORY_GROUP.INDUSTRY,
        depth: null,
    },
    {
        id: 'JOB_PLATFORMS',
        name: 'Job platforms',
        parentCategoryId: null,
        group: CATEGORY_GROUP.INDUSTRY,
        depth: null,
    },
    {
        id: 'NEWS_AND_ARTICLES',
        name: 'News & articles',
        parentCategoryId: null,
        group: CATEGORY_GROUP.INDUSTRY,
        depth: null,
    },
    {
        id: 'MAPS_AND_LOCAL_BUSINESSES',
        name: 'Maps & local businesses',
        parentCategoryId: null,
        group: CATEGORY_GROUP.INDUSTRY,
        depth: null,
    },
    {
        id: 'B2B_AND_COMPANY_DATA',
        name: 'B2B & company data',
        parentCategoryId: null,
        group: CATEGORY_GROUP.INDUSTRY,
        depth: null,
    },
    {
        id: 'SEARCH_ENGINES_AND_SEO',
        name: 'Search engines & SEO',
        parentCategoryId: null,
        group: CATEGORY_GROUP.INDUSTRY,
        depth: null,
    },
    {
        id: 'FINANCE_AND_CRYPTO',
        name: 'Finance & crypto',
        parentCategoryId: null,
        group: CATEGORY_GROUP.INDUSTRY,
        depth: null,
    },
    {
        id: 'REVIEW_SITES',
        name: 'Review sites',
        parentCategoryId: null,
        group: CATEGORY_GROUP.INDUSTRY,
        depth: null,
    },
    {
        id: 'AI_AND_ML',
        name: 'AI & ML',
        parentCategoryId: null,
        group: CATEGORY_GROUP.INDUSTRY,
        depth: null,
    },
    {
        id: 'ENTERTAINMENT_AND_STREAMING',
        name: 'Entertainment & streaming',
        parentCategoryId: null,
        group: CATEGORY_GROUP.INDUSTRY,
        depth: null,
    },
    {
        id: 'GOVERNMENT_AND_PUBLIC_DATA',
        name: 'Government & public data',
        parentCategoryId: null,
        group: CATEGORY_GROUP.INDUSTRY,
        depth: null,
    },
    {
        id: 'AUTOMOTIVE',
        name: 'Automotive',
        parentCategoryId: null,
        group: CATEGORY_GROUP.INDUSTRY,
        depth: null,
    },
    {
        id: 'CLASSIFIEDS_AND_PEER_TO_PEER',
        name: 'Classifieds & peer-to-peer',
        parentCategoryId: null,
        group: CATEGORY_GROUP.INDUSTRY,
        depth: null,
    },
    {
        id: 'DEVELOPER_AND_TECH',
        name: 'Developer & tech',
        parentCategoryId: null,
        group: CATEGORY_GROUP.INDUSTRY,
        depth: null,
    },
    {
        id: 'GENERIC_SCRAPERS',
        name: 'Generic scrapers',
        parentCategoryId: null,
        group: CATEGORY_GROUP.INDUSTRY,
        depth: null,
    },
] as const satisfies readonly ActorCategoryShape[];

export const DOMAIN_CATEGORIES = [
    {
        id: 'FACEBOOK',
        name: 'Facebook',
        parentCategoryId: null,
        group: CATEGORY_GROUP.DOMAIN,
        depth: null,
    },
    {
        id: 'INSTAGRAM',
        name: 'Instagram',
        parentCategoryId: null,
        group: CATEGORY_GROUP.DOMAIN,
        depth: null,
    },
    {
        id: 'X_TWITTER',
        name: 'X (Twitter)',
        parentCategoryId: null,
        group: CATEGORY_GROUP.DOMAIN,
        depth: null,
    },
    {
        id: 'TIKTOK',
        name: 'TikTok',
        parentCategoryId: null,
        group: CATEGORY_GROUP.DOMAIN,
        depth: null,
    },
    {
        id: 'YOUTUBE',
        name: 'YouTube',
        parentCategoryId: null,
        group: CATEGORY_GROUP.DOMAIN,
        depth: null,
    },
    {
        id: 'LINKEDIN',
        name: 'LinkedIn',
        parentCategoryId: null,
        group: CATEGORY_GROUP.DOMAIN,
        depth: null,
    },
    {
        id: 'AMAZON',
        name: 'Amazon',
        parentCategoryId: null,
        group: CATEGORY_GROUP.DOMAIN,
        depth: null,
    },
    {
        id: 'EBAY',
        name: 'eBay',
        parentCategoryId: null,
        group: CATEGORY_GROUP.DOMAIN,
        depth: null,
    },
    {
        id: 'ETSY',
        name: 'Etsy',
        parentCategoryId: null,
        group: CATEGORY_GROUP.DOMAIN,
        depth: null,
    },
    {
        id: 'ALIEXPRESS',
        name: 'AliExpress',
        parentCategoryId: null,
        group: CATEGORY_GROUP.DOMAIN,
        depth: null,
    },
    {
        id: 'GOOGLE',
        name: 'Google',
        parentCategoryId: null,
        group: CATEGORY_GROUP.DOMAIN,
        depth: null,
    },
    {
        id: 'BOOKING_COM',
        name: 'Booking.com',
        parentCategoryId: null,
        group: CATEGORY_GROUP.DOMAIN,
        depth: null,
    },
    {
        id: 'TRIPADVISOR',
        name: 'Tripadvisor',
        parentCategoryId: null,
        group: CATEGORY_GROUP.DOMAIN,
        depth: null,
    },
    {
        id: 'REDDIT',
        name: 'Reddit',
        parentCategoryId: null,
        group: CATEGORY_GROUP.DOMAIN,
        depth: null,
    },
    {
        id: 'YELP',
        name: 'Yelp',
        parentCategoryId: null,
        group: CATEGORY_GROUP.DOMAIN,
        depth: null,
    },
    {
        id: 'ZILLOW',
        name: 'Zillow',
        parentCategoryId: null,
        group: CATEGORY_GROUP.DOMAIN,
        depth: null,
    },
    {
        id: 'GOOGLE_MAPS',
        name: 'Google Maps',
        parentCategoryId: 'MAPS_AND_LOCAL_BUSINESSES',
        group: CATEGORY_GROUP.DOMAIN,
        depth: null,
    },
    {
        id: 'AIRBNB',
        name: 'Airbnb',
        parentCategoryId: 'TRAVEL_AND_HOSPITALITY',
        group: CATEGORY_GROUP.DOMAIN,
        depth: null,
    },
    {
        id: 'PINTEREST',
        name: 'Pinterest',
        parentCategoryId: 'SOCIAL_MEDIA',
        group: CATEGORY_GROUP.DOMAIN,
        depth: null,
    },
    {
        id: 'SHOPIFY',
        name: 'Shopify',
        parentCategoryId: 'ECOMMERCE',
        group: CATEGORY_GROUP.DOMAIN,
        depth: null,
    },
    {
        id: 'GITHUB',
        name: 'GitHub',
        parentCategoryId: 'DEVELOPER_AND_TECH',
        group: CATEGORY_GROUP.DOMAIN,
        depth: null,
    },
    {
        id: 'SNAPCHAT',
        name: 'Snapchat',
        parentCategoryId: 'SOCIAL_MEDIA',
        group: CATEGORY_GROUP.DOMAIN,
        depth: null,
    },
    {
        id: 'TRUSTPILOT',
        name: 'Trustpilot',
        parentCategoryId: 'REVIEW_SITES',
        group: CATEGORY_GROUP.DOMAIN,
        depth: null,
    },
    {
        id: 'TELEGRAM',
        name: 'Telegram',
        parentCategoryId: 'SOCIAL_MEDIA',
        group: CATEGORY_GROUP.DOMAIN,
        depth: null,
    },
    {
        id: 'REALTOR_COM',
        name: 'Realtor.com',
        parentCategoryId: 'REAL_ESTATE',
        group: CATEGORY_GROUP.DOMAIN,
        depth: null,
    },
    {
        id: 'THREADS',
        name: 'Threads',
        parentCategoryId: 'SOCIAL_MEDIA',
        group: CATEGORY_GROUP.DOMAIN,
        depth: null,
    },
    {
        id: 'YELLOW_PAGES',
        name: 'Yellow Pages',
        parentCategoryId: 'MAPS_AND_LOCAL_BUSINESSES',
        group: CATEGORY_GROUP.DOMAIN,
        depth: null,
    },
    {
        id: 'GLASSDOOR',
        name: 'Glassdoor',
        parentCategoryId: 'JOB_PLATFORMS',
        group: CATEGORY_GROUP.DOMAIN,
        depth: null,
    },
    {
        id: 'INDEED',
        name: 'Indeed',
        parentCategoryId: 'JOB_PLATFORMS',
        group: CATEGORY_GROUP.DOMAIN,
        depth: null,
    },
    {
        id: 'CRUNCHBASE',
        name: 'Crunchbase',
        parentCategoryId: 'B2B_AND_COMPANY_DATA',
        group: CATEGORY_GROUP.DOMAIN,
        depth: null,
    },
    {
        id: 'SPOTIFY',
        name: 'Spotify',
        parentCategoryId: 'ENTERTAINMENT_AND_STREAMING',
        group: CATEGORY_GROUP.DOMAIN,
        depth: null,
    },
    {
        id: 'GOOGLE_PLAY',
        name: 'Google Play',
        parentCategoryId: 'DEVELOPER_AND_TECH',
        group: CATEGORY_GROUP.DOMAIN,
        depth: null,
    },
    {
        id: 'APPLE_APP_STORE',
        name: 'Apple App Store',
        parentCategoryId: 'DEVELOPER_AND_TECH',
        group: CATEGORY_GROUP.DOMAIN,
        depth: null,
    },
    {
        id: 'WALMART',
        name: 'Walmart',
        parentCategoryId: 'ECOMMERCE',
        group: CATEGORY_GROUP.DOMAIN,
        depth: null,
    },
    {
        id: 'UPWORK',
        name: 'Upwork',
        parentCategoryId: 'JOB_PLATFORMS',
        group: CATEGORY_GROUP.DOMAIN,
        depth: null,
    },
    {
        id: 'BING',
        name: 'Bing',
        parentCategoryId: 'SEARCH_ENGINES_AND_SEO',
        group: CATEGORY_GROUP.DOMAIN,
        depth: null,
    },
    {
        id: 'VK',
        name: 'VK',
        parentCategoryId: 'SOCIAL_MEDIA',
        group: CATEGORY_GROUP.DOMAIN,
        depth: null,
    },
    {
        id: 'WHATSAPP',
        name: 'WhatsApp',
        parentCategoryId: 'SOCIAL_MEDIA',
        group: CATEGORY_GROUP.DOMAIN,
        depth: null,
    },
    {
        id: 'BLUESKY',
        name: 'Bluesky',
        parentCategoryId: 'SOCIAL_MEDIA',
        group: CATEGORY_GROUP.DOMAIN,
        depth: null,
    },
    {
        id: 'DISCORD',
        name: 'Discord',
        parentCategoryId: 'SOCIAL_MEDIA',
        group: CATEGORY_GROUP.DOMAIN,
        depth: null,
    },
    {
        id: 'SUBSTACK',
        name: 'Substack',
        parentCategoryId: 'NEWS_AND_ARTICLES',
        group: CATEGORY_GROUP.DOMAIN,
        depth: null,
    },
    {
        id: 'IMDB',
        name: 'IMDb',
        parentCategoryId: 'ENTERTAINMENT_AND_STREAMING',
        group: CATEGORY_GROUP.DOMAIN,
        depth: null,
    },
] as const satisfies readonly ActorCategoryShape[];

export const OUTPUT_CATEGORIES = [
    {
        id: 'VIDEOS',
        name: 'Videos',
        parentCategoryId: null,
        group: CATEGORY_GROUP.OUTPUT,
        depth: null,
    },
    {
        id: 'TRANSCRIPTS',
        name: 'Transcripts',
        parentCategoryId: null,
        group: CATEGORY_GROUP.OUTPUT,
        depth: null,
    },
    {
        id: 'PROFILES',
        name: 'Profiles',
        parentCategoryId: null,
        group: CATEGORY_GROUP.OUTPUT,
        depth: null,
    },
    {
        id: 'PLACES',
        name: 'Places',
        parentCategoryId: null,
        group: CATEGORY_GROUP.OUTPUT,
        depth: null,
    },
    {
        id: 'PRODUCTS',
        name: 'Products',
        parentCategoryId: null,
        group: CATEGORY_GROUP.OUTPUT,
        depth: null,
    },
    {
        id: 'COMMENTS',
        name: 'Comments',
        parentCategoryId: null,
        group: CATEGORY_GROUP.OUTPUT,
        depth: null,
    },
    {
        id: 'REVIEWS',
        name: 'Reviews',
        parentCategoryId: null,
        group: CATEGORY_GROUP.OUTPUT,
        depth: null,
    },
    {
        id: 'CONTACT_DETAILS',
        name: 'Contact Details',
        parentCategoryId: null,
        group: CATEGORY_GROUP.OUTPUT,
        depth: null,
    },
    {
        id: 'REAL_ESTATE_LISTINGS',
        name: 'Real Estate Listings',
        parentCategoryId: null,
        group: CATEGORY_GROUP.OUTPUT,
        depth: null,
    },
    {
        id: 'JOB_LISTINGS',
        name: 'Job Listings',
        parentCategoryId: null,
        group: CATEGORY_GROUP.OUTPUT,
        depth: null,
    },
    {
        id: 'SOCIAL_POSTS',
        name: 'Social Posts',
        parentCategoryId: null,
        group: CATEGORY_GROUP.OUTPUT,
        depth: null,
    },
    {
        id: 'FINANCIAL_DATA',
        name: 'Financial Data',
        parentCategoryId: null,
        group: CATEGORY_GROUP.OUTPUT,
        depth: null,
    },
    {
        id: 'COMPANY_DATA',
        name: 'Company Data',
        parentCategoryId: null,
        group: CATEGORY_GROUP.OUTPUT,
        depth: null,
    },
    {
        id: 'NEWS_ARTICLES',
        name: 'News & Articles',
        parentCategoryId: null,
        group: CATEGORY_GROUP.OUTPUT,
        depth: null,
    },
    {
        id: 'SEO_ANALYTICS',
        name: 'SEO & Analytics Data',
        parentCategoryId: null,
        group: CATEGORY_GROUP.OUTPUT,
        depth: null,
    },
    {
        id: 'EVENTS',
        name: 'Events',
        parentCategoryId: null,
        group: CATEGORY_GROUP.OUTPUT,
        depth: null,
    },
    {
        id: 'SEARCH_RESULTS',
        name: 'Search Results',
        parentCategoryId: null,
        group: CATEGORY_GROUP.OUTPUT,
        depth: null,
    },
] as const satisfies readonly ActorCategoryShape[];

export const LABEL_CATEGORIES = [
    {
        id: 'OPEN_SOURCE',
        name: 'Open source',
        parentCategoryId: null,
        group: CATEGORY_GROUP.LABEL,
        depth: null,
    },
    {
        id: 'AGENT',
        name: 'Agent',
        parentCategoryId: null,
        group: CATEGORY_GROUP.LABEL,
        depth: null,
    },
    {
        id: 'AUTOMATION',
        name: 'Automation',
        parentCategoryId: null,
        group: CATEGORY_GROUP.LABEL,
        depth: null,
    },
    {
        id: 'INTEGRATION',
        name: 'Integration',
        parentCategoryId: null,
        group: CATEGORY_GROUP.LABEL,
        depth: null,
    },
    {
        id: 'MCP_SERVER',
        name: 'MCP server',
        parentCategoryId: null,
        group: CATEGORY_GROUP.LABEL,
        depth: null,
    },
    {
        id: 'AI_TOOLS',
        name: 'AI tools',
        parentCategoryId: null,
        group: CATEGORY_GROUP.LABEL,
        depth: null,
    },
] as const satisfies readonly ActorCategoryShape[];
export const ALL_CATEGORIES = [
    ...USE_CASE_CATEGORIES,
    ...LABEL_CATEGORIES,
    ...INDUSTRY_CATEGORIES,
    ...DOMAIN_CATEGORIES,
    ...OUTPUT_CATEGORIES,
] as const satisfies readonly ActorCategoryShape[];

export type CategoryId = (typeof ALL_CATEGORIES)[number]['id'];

export type UseCaseCategoryId = (typeof USE_CASE_CATEGORIES)[number]['id'];

export type ActorCategoryDefinition = ActorCategoryShape & { id: CategoryId; parentCategoryId: CategoryId | null };

export const CATEGORY_ID = Object.fromEntries(ALL_CATEGORIES.map(({ id }) => [id, id])) as {
    readonly [K in CategoryId]: K;
};

export const CATEGORY_BY_ID: ReadonlyMap<CategoryId, ActorCategoryDefinition> = new Map(
    ALL_CATEGORIES.map((category) => [category.id, category]),
);

export const isCategoryId = (value: string): value is CategoryId => CATEGORY_BY_ID.has(value as CategoryId);

/** Returns the given category ID and all its ancestor IDs. Order: [self, parent, grandparent, …]. */
export const getCategoryWithAncestorIds = (id: CategoryId): CategoryId[] => {
    const result: CategoryId[] = [];
    let current: ActorCategoryDefinition | undefined = CATEGORY_BY_ID.get(id);
    while (current) {
        result.push(current.id);
        current = current.parentCategoryId ? CATEGORY_BY_ID.get(current.parentCategoryId) : undefined;
    }
    return result;
};

/** Expands category IDs with all their ancestors, deduped. */
export const expandWithAncestorIds = (ids: CategoryId[]): CategoryId[] => [
    ...new Set(ids.flatMap(getCategoryWithAncestorIds)),
];
